### ISSUE TITLE
Is there any easier way to make "advanced configure"?

### ISSUE THREAD

**Issue by marslo** [luochen1990/rainbow#1]
I just want to know, if there any way can make 'Advanced configure' easier. For example, my vim have different color settings for different $TERM value:

```
if has('gui_running') || 'xterm-256color' == $TERM
  let g:rainbow_conf = extend({
  \   'guifgs' : ['#6A5ACD', '#B22222', '#C0FF3E', '#EEC900', '#9A32CD', '#EE7600', '#98fb98', '#686868'],
  \   'ctermfgs' : ['141', '196', '112', '208', '129', '166', '85', '237'],
  \}, exists('g:rainbow_conf')? g:rainbow_conf : {})
else
  let g:rainbow_conf = extend({
  \   'ctermfgs' = ['lightblue', 'lightgreen', 'yellow', 'red', 'magenta'],
  \}, exists('g:rainbow_conf')? g:rainbow_conf : {})
endif
```

However, there are many redundancy code in my configures.
Is there any way can make advanced setting as easier as this one (https://github.com/oblitum/rainbow#advanced-configuration)?

**Comment by guanjianzhe** [comment]
I really need to solve this problem.

I copy your code, but reported:

E121: Undefined variable: background
E15: Invalid expression: {   'ctermfgs': ( background=="light"? darkcolors : lightcolors)}
