### ISSUE TITLE
Unknown function: rainbow#load wih Racket ftdetect on

### ISSUE THREAD

**Issue by mwgkgk** [luochen1990/rainbow#103]
When dealing with racket filetype detection,
```
au BufRead,BufNewFile *.rkt,*.rktl  set filetype=racket
```
(as seen in https://github.com/wlangstroth/vim-racket/blob/master/ftdetect/racket.vim),

when opening an `.rkt` file either as an argument or from a running vim, I get:
```
Error detected while processing FileType Auto commands for "racket":
E117: Unknown function: rainbow#load
```
Which is weird because there does not seem to even be a function called `rainbow#load`: it's actually `rainbow_main#load`. Without ftdetect, `.rkt` files identify as scheme, due to this line found in `/usr/share/vim/vim81/filetype.vim`:
```
" Scheme
au BufNewFile,BufRead *.scm,*.ss,*.rkt		setf scheme
```
Changing `g:rainbow_conf` does not seem to have an effect. Changing the filetype from commandline produces same errors when changing any file to racket, lisp, lfe, clojure, hy (e.g. `:se ft=racket`), but not scheme, or non-sexp languages.

I'm kind of lost here and would appreciate any pointers :)

**Comment by luochen1990** [comment]
Sorry but I cannot reproduce this problem, maybe you can try to search `rainbow#load` in your `.vimrc`.

**Comment by mwgkgk** [comment]
Wow that's embarrassing! I have .vimrc split into multiple files, and didn't realize I'm not grepping some of them. One contained the `rainbow#load` snippet, likely a remainder from another plugin that I temporarily tested in the past. Thank you :)
