### ISSUE TITLE
Rainbow works on single file component of Vue

### ISSUE THREAD

**Issue by pablocattaneo** [luochen1990/rainbow#107]
Hi there!

First of all thanks you for your work!

I'm here to ask for a new features, it would be great if the plugin could works with vue files, I mean with single file component vue https://vuejs.org/v2/guide/single-file-components.html. Right now it doesn't work.

![image](https://user-images.githubusercontent.com/11772956/48959208-bc402300-ef42-11e8-81b0-affa17a184bd.png)

I would really appreciate it!

**Comment by luochen1990** [comment]
Maybe you can try to config your plugin like this:
```
let g:rainbow_conf = {
\	'separately': {
\		'vue': {
\			'parentheses': ['start=/{/ end=/}/ fold contains=@javaScript containedin=@javaScript', 'start=/(/ end=/)/ fold contains=@javaScript containedin=@javaScript'],
\		},
\	}
\}
```
but the official syntax plugin for vue defined `jsParens` as keyword so the effect of this plugin is overlapped, unfortunately

**Comment by luochen1990** [comment]
maybe you can try to execute `syntax clear jsParens` with autocmd.

**Comment by invernizzi** [comment]
I'm resurrecting this closed issue for a brief update to anybody looking for this solution.
The above configuration works great for JavaScript code in Vue components, but it doesn't highlight HTML.
If you want HTML tags to be colorized too, like below, use this config:
```
let g:rainbow_conf = {
\	'separately': {
\		'vue': {
\			'parentheses': ['start=/{/ end=/}/ fold contains=@javaScript containedin=@javaScript', 'start=/(/ end=/)/ fold contains=@javaScript containedin=@javaScript', 'start=/\v\<((script|style|area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
\		},
\	}
\}
```
Happy double rainbows!

![image](https://user-images.githubusercontent.com/140925/64878597-b9fda100-d608-11e9-9324-2dbfe631f794.png)


@luochen1990 : Thanks for this library! Consider putting the above code into your default config, as Vue is the most popular JS framework (at the moment).
