### ISSUE TITLE
No operator highlighting outside of top-level parenthesis

### ISSUE THREAD

**Issue by tmsbrg** [luochen1990/rainbow#11]
Version 2.51.1 of rainbow parenthesis improved had operators outside of all parentheses get highlighted with the deepest parenthesis color(usually purple).

I just updated to the newest version(3.1.2) and found out this was removed( https://dl.dropboxusercontent.com/u/26359447/rainbows_in_python.png ). I'm not sure if that was intentional or not but I'd prefer it back in. I looked at the script to see if I could change it or re-enable it but couldn't find anything.

Note:

I changed the operators part of rainbow_conf to 

```
\   'operators': '_,\|=\|+\|\*\|-\|\.\|;\||\|&\|?\|:\|<\|>\|%\|/[^/]_',
```

so i could get the default operator highlighting back that was in the old version. Not sure if that's the right way to do it but it seems to work

**Comment by zackelflac** [comment]
I found this post useful.
If I may, you should put this sacred line in your Readme ;-)
(Actually Oblitum seems unoptimized for operators highlighting whereas your plugin version work well, thanks for that by the way!)
