### ISSUE TITLE
Color matching breaks after ~100 lines

### ISSUE THREAD

**Issue by Taceor** [luochen1990/rainbow#110]
### **Description**
After around 100 lines (in a long CLOS class definition) the paren highlighting breaks. Second level nested parens are highlighted as 1st level (top-level) parens. Paredit functionality provided by slimv still functions correctly.

If I hold `j` to scroll the entire length of the definition, the colors adjust and match correctly again. If I use `()` `{}` or `:line-number` to jump to file positions, the colors break again.

### **To Reproduce**
Here's a mostly trimmed .vimrc file
```
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'kovisoft/slimv'
Plugin 'luochen1990/rainbow'
Plugin 'altercation/vim-colors-solarized'
call vundle#end()
filetype plugin indent on
syntax on
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set background=dark
colorscheme solarized
set t_Co=256
set nosmarttab
set viminfo='1000,f1,<500
set hidden
set visualbell
set fdm=syntax
let g:paredit_matchlines = 1000
let g:rainbow_active = 1
```

### **Expected behavior**
I expect parens to match. In paredit (part of slimv), there's a g:paredit_matchlines variable that can be set to change the max number of lines to scan for a matching paren. I tried to find similar for rainbow but was not successful. 

### **Screenshots**
Top of file
![image](https://user-images.githubusercontent.com/10453720/53046864-4880ba00-344e-11e9-98bc-a243750cff27.png)

Bottom of file. Line 352 in this example.
![image](https://user-images.githubusercontent.com/10453720/53046831-34d55380-344e-11e9-8650-01ece0de1a26.png)

**Comment by luochen1990** [comment]
This is a feature of Vim's syntax highlighting, see `:h syn-sync` for more details.

**Comment by Taceor** [comment]
Thank you, @luochen1990. For anyone else that arrives here, I was able to resolve the issue by setting `:syntax sync fromstart` though you should note this is a slower process.
