### ISSUE TITLE
An error occurs when changing the setting name

### ISSUE THREAD

**Issue by yuki-ycino** [luochen1990/rainbow#113]
### **Describe the bug**

The part to be written as cterms is cterm

`len(conf.cterm)` -> `len(conf.cterms)`

https://github.com/luochen1990/rainbow/blob/master/autoload/rainbow_main.vim#L86

### **To Reproduce**

.vimrc

```
let g:rainbow_active           = 1
let g:rainbow_conf             = {}
let g:rainbow_conf.cterms      = ['']
let g:rainbow_conf.ctermfgs    = ['yellow', 'darkred', 'darkgreen', 'darkblue']
let g:rainbow_conf.guis        = ['']
let g:rainbow_conf.guifgs      = ['#BD9D0B', '#B3427E', '#5B9C14', '#3E7C94']
let g:rainbow_conf.operator    = '_,_'
let g:rainbow_conf.parentheses = ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold']
```

### **Screenshots**

<img width="1680" alt="2019-03-01 18 50 24" src="https://user-images.githubusercontent.com/5423775/53630271-08da7f00-3c53-11e9-9e74-dea5b57951f7.png">

**Comment by drn** [comment]
Linking the issue / PR - https://github.com/luochen1990/rainbow/pull/112 resolves

**Comment by j5shi** [comment]
Hi, it seems the fix has not yet been merged to master? I'm still seeing this issue with the most recent commit (0e5a6d7fe050f293ce89a9ba8d586f86b1badf45 - 2019-03-01 15:16 +0800 LuoChen         o [master] {origin/HEAD} {origin/master} fix: recover vim's default config).
