### ISSUE TITLE
Error happens when launch

### ISSUE THREAD

**Issue by xaljer** [luochen1990/rainbow#118]
### **Describe the bug**
I use demo configs in README, after update plugin recently, error happens when launch.
Neovim 0.4 (neovim-qt) on Windows10
### **To Reproduce**
Steps to reproduce the behavior, **A piece of code to demo the issue is appreciated**.
open the neovim-qt, error is reported.
### **Screenshots**
<img width="1035" alt="snipaste_2019-03-03_12-01-47" src="https://user-images.githubusercontent.com/8309631/53690794-38e96580-3dac-11e9-953a-4534df242aee.png">

### **Additional context**
**Are you using some third-party syntax plugins?** Add any other context about the problem here.

**Comment by walkingsparrow** [comment]
Me too. So I now disabled this plugin. I hope this could be fixed soon.

**Comment by laomafeima** [comment]
Linking the issue / PR - #112 resolves.
