### ISSUE TITLE
[Bug] rainbow does not work with vim8.1

### ISSUE THREAD

**Issue by laoshaw** [luochen1990/rainbow#127]
Tried it alone with vim8.1(in case some other plugins is in conflict), this does not work, i.e. no brackets are rainbow colored at all

**Comment by luochen1990** [comment]
1. Is there any error message?
2. what filetype have you tried?
3. do you have `let g:rainbow_active = 1` in your vimrc?

**Comment by laoshaw** [comment]
I thought let g:rainbow_active = 1 is the default, just added it and it works, thanks.
