### ISSUE TITLE
Compatibilty with Kotlin

### ISSUE THREAD

**Issue by BeakBryno7** [luochen1990/rainbow#149]
Hey,

Anyone got any ideas to get Rainbow Parentheses working with Kotlin files? I have tried adding **Kotlin** and **kt** to `au FileType c,cpp,objc,objcpp,go,rust,python,ruby,javascript,java,vim call rainbow#load()` but it was futile. Rainbow Parenthesis can't identify the parentheses nor the braces of sorts.

Thanks,
Sam

**Comment by luochen1990** [comment]
You don't need `au` command, you can do what you want via configuration:

```
let g:rainbow_conf = {
\	'separately': {
\		'*': 0,
\		'c': {},
\		'cpp': {},
\		'kotlin': {}
\	}
\}
```

If you are not sure about the exact name of your filetype, just edit one file and `:echo &ft`.
