### ISSUE TITLE
rainbow in `:terminal`

### ISSUE THREAD

**Issue by iambrj** [luochen1990/rainbow#152]
**Is your feature request related to a problem? Please describe.**
Unable to use rainbow when in `:terminal`

**Describe the solution you'd like**
rainbow should work in `:terminal`

**Describe alternatives you've considered**
None.

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/29101670/96665158-e2aaab00-1371-11eb-98ff-ef380f14d8a5.png)

**Comment by luochen1990** [comment]
Please try to set the filetype, like `:set ft=bash`

**Comment by iambrj** [comment]
That seems to do the trick, thank you! :smile:
