### ISSUE TITLE
[Bug] An edge case when using JS regex

### ISSUE THREAD

**Issue by tejasvi** [luochen1990/rainbow#157]
### **Describe the bug**
Incorrect color coding.

### **To Reproduce**
File: `bug.js`, filetype=javascript
```
data.replaceAll(/[\\\/:*?"<>|]/g, '-')
```

Steps:
1. Open file via `vim bug.js`
2. See the color of outermost `(` and `)` 

### **Expected behavior**
The color should be same.

### **Screenshots**
![image](https://user-images.githubusercontent.com/45873379/107011742-16dd9680-67be-11eb-9ea9-8822b74330ff.png)

**Comment by luochen1990** [comment]
It seems that your javascript syntax plugin doesn't recognize the `/regex/` syntax

**Comment by tejasvi** [comment]
That explains it then. I am using Vim's inbuilt JS syntax implementation. `%` is not working correctly as well. Anyway, thanks for pointer!
