### ISSUE TITLE
[help wanted] Can not work in vue files (Already configured)

### ISSUE THREAD

**Issue by niuiic** [luochen1990/rainbow#162]
Hi, I have configured for vue files accroding to [#107](https://github.com/luochen1990/rainbow/issues/107)。But it seems that the plugin failed to work.

My configuration.

```
	\ 		'vue' : {
	\			'parentheses': ['start=/{/ end=/}/ fold contains=@javaScript containedin=@javaScript', 'start=/(/ end=/)/ fold contains=@javaScript containedin=@javaScript', 'start=/\v\<((script|style|area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
	\		}
```

neovim version

```
$ nvim -v         
NVIM v0.4.4
Build type: Gentoo
Lua 5.1
Compilation: /usr/lib/ccache/bin/clang -march=native -O2 -pipe -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/var/tmp/portage/app-editors/neovim-0.4.4-r100/work/neovim-0.4.4_build/config -I/var/tmp/portage/app-editors/neovim-0.4.4-r100/work/neovim-0.4.4/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.4.4-r100/work/neovim-0.4.4_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.4.4-r100/work/neovim-0.4.4_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Before configuration

![image](https://user-images.githubusercontent.com/63799565/117947609-f08e4080-b342-11eb-8617-811dfb42d0c3.png)

After configuration（It works in html code, but not in js code）
![image](https://user-images.githubusercontent.com/63799565/117947414-c0df3880-b342-11eb-86bd-6f00c60cbb65.png)

It works well in other file types.

These could be helpful.

![image](https://user-images.githubusercontent.com/63799565/117948048-5a0e4f00-b343-11eb-83c7-6cff11e727f6.png)
![image](https://user-images.githubusercontent.com/63799565/117948119-6a262e80-b343-11eb-953f-d9a1458a3c56.png)
![image](https://user-images.githubusercontent.com/63799565/117948154-714d3c80-b343-11eb-8af0-6ee88edabd7f.png)
![image](https://user-images.githubusercontent.com/63799565/117948201-7a3e0e00-b343-11eb-9250-a48e6ad0da66.png)
![image](https://user-images.githubusercontent.com/63799565/117948260-8b871a80-b343-11eb-913d-191165e0d997.png)

**Comment by luochen1990** [comment]
because `<script>` is a special tag in HTML, and vim's default syntax file did some special things to them...  

Maybe the `trouble shooting` section in README can help

**Comment by niuiic** [comment]
I'm sorry, I don't quite understand those things in trouble shooting.

I have tried a few times and found that it doesn’t work at all.

And this configurations works in [#107](https://github.com/luochen1990/rainbow/issues/107).  Is this the difference between vim and neovim?

![image](https://user-images.githubusercontent.com/63799565/117950103-6d221e80-b345-11eb-8a40-5184726e6fbb.png)

**Comment by niuiic** [comment]
I found that my vue syntax highlighting plugin interfered with syntax highlighting. And rainbow would not work in vue files, both in html codes and js codes.

Then I have to give up using rainbow in the vue file whether or not the above problem is solved.

I feel a little sorry, and thank you for your help.
