### ISSUE TITLE
how to disbale in nerdtree?

### ISSUE THREAD

**Issue by mickro** [luochen1990/rainbow#165]
When auto-enabled I got my nerdtree icons plugin less readeable
![image](https://user-images.githubusercontent.com/51155/123396308-74258900-d5a1-11eb-9a16-9ded12138824.png)

When it is disabled it looks better
![image](https://user-images.githubusercontent.com/51155/123396382-8a334980-d5a1-11eb-8d66-24455d32feda.png)

Generally I do not want to enable rainbow plugin in the nerdtree buffer. Is there a simple way to specify this?

**Comment by lidulibai** [comment]
#92

**Comment by timsu92** [comment]
Fixed by #185. Please check and change your settings accordingly.

**Comment by luochen1990** [comment]
I will close this issue since the related PR is merged, if there is still any issue, please feel free to reopen it.
