### ISSUE TITLE
[Bug] extra parentheses '[]' around the directory  icon when using rainbow with 'preservim/nerdtree'

### ISSUE THREAD

**Issue by XingZhiang** [luochen1990/rainbow#182]
### **Describe the bug**
there will have extra parentheses '[]' around the directory  icon when using rainbow with ['preservim/nerdtree'](https://github.com/preservim/nerdtree)

[![Screenshot-20220507-210004.png](https://i.postimg.cc/C5qDbtvJ/Screenshot-20220507-210004.png)](https://postimg.cc/zHqVrdYR)

**Comment by hungpham3112** [comment]
> What is the filetype (use `:set ft?` to show it) of the nerdtree buffer?
> 
> If you know that, you can disable rainbow for this filetype specificly (See README.md about configuration).

```
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                             Plugin: Rainbow                                "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:rainbow_active = 1 
let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}'], ['<', '>']]
let g:rainbow_conf = { 
    \ 'nerdtree': 0,
    \ }
```
I disabled this plugin with nerdtree but still see the parentheses.

![image](https://user-images.githubusercontent.com/75968004/169450550-c693ef78-2df6-4e1a-b076-1a5e9037232c.png)

**Comment by luochen1990** [comment]
What's your output of `:set ft?` when you focus on the nerdtree buffer?

**Comment by luochen1990** [comment]
@hungpham3112 Oh, it's the syntax of your configuration!   `'nerdtree': 0` should be inside the `seperately` block .

**Comment by luochen1990** [comment]
See [here](https://github.com/luochen1990/rainbow/issues/40#issuecomment-160296377) for reference

**Comment by hungpham3112** [comment]
> @hungpham3112 Oh, it's the syntax of your configuration! `'nerdtree': 0` should be inside the `seperately` block .

I got it, but it also change the color of commas in code. How can I configure it? Thanks

![image](https://user-images.githubusercontent.com/75968004/169944043-c278ed80-2eab-49b9-8aeb-0a0e7771d29b.png)

**Comment by luochen1990** [comment]
I cannot figure out what's your current issue,  If you are talking about a new issue, please open a new one and describe your  observation and expectation so that I can help you,  thank you.

**Comment by hungpham3112** [comment]
> I cannot figure out what's your current issue, If you are talking about a new issue, please open a new one and describe your observation and expectation so that I can help you, thank you.

I mean how can I turn off colorscheme for commas. it just appear when I run: `RainbowToggle`
