### ISSUE TITLE
[Bug] Brake comments colorization

### ISSUE THREAD

**Issue by Curs3W4ll** [luochen1990/rainbow#183]
### **Describe the bug**

Removing comments grey colorizations when comments contain operators

### **To Reproduce**

File: `bug.cpp`, filetype=cpp
```
int main() {
    int x = 1;
    // This is a comment

    int y = 2;
    /*
     * Multiline comment
     */
    return 0;
}
```

Steps:
1. Open file via `vim bug.js`
2. See the colors of commented sections

### **Expected behavior**
Comments should be grey as they are without the rainbow plugin

### **Screenshots**
Expected
![image](https://user-images.githubusercontent.com/72013831/169103961-47435f7e-0389-4c40-ab16-95c7e6f4d6ae.png)

With rainbow toggled OFF
![image](https://user-images.githubusercontent.com/72013831/169104037-f6fae296-c783-4a4d-b77d-e4a9755b5133.png)

With rainbow toggled ON
![image](https://user-images.githubusercontent.com/72013831/169104097-5797b08f-5272-4ab3-a499-e36211da637d.png)

### **Additional context**
I use that config
```
let g:rainbow_active = 1 " Load vim-rainbow for all the files

let g:rainbow_conf = {
\	'guifgs': ['magenta', 'coral2', 'gold', 'deepskyblue', 'slateblue'],
\	'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
\	'guis': [''],
\	'cterms': [''],
\	'operators': '_,\|\.\|+\|-\|*\|\/\|%\|;\|=\|!\|<\|>_',
\	'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
\	'separately': {
\		'*': {},
\		'markdown': {
\			'parentheses_options': 'containedin=markdownCode contained',
\		},
\		'lisp': {
\			'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
\		},
\		'haskell': {
\			'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/\v\{\ze[^-]/ end=/}/ fold'],
\		},
\		'vim': {
\			'parentheses_options': 'containedin=vimFuncBody',
\		},
\		'perl': {
\			'syn_name_prefix': 'perlBlockFoldRainbow',
\		},
\		'stylus': {
\			'parentheses': ['start=/{/ end=/}/ fold contains=@colorableGroup'],
\		},
\       'nerdtree': 0,
\		'css': 0,
\	}
\}
```

**Comment by luochen1990** [comment]
Try to find out (you can use the tool in README.md) the syntax name of comment  (when rainbow is disabled), and add something like following to your configuration ( replace `xxxComment` to the real one ) :

```
let g:rainbow_conf = {
\	'separately': {
\		'cpp': {
\			'parentheses_options': 'contains=@xxxComment',
\		}
\	}
\}
```

**Comment by Curs3W4ll** [comment]
with `:hi`, I found out that comments are identified with the syntax name `Comment`

![image](https://user-images.githubusercontent.com/72013831/169985803-1b2c4475-a138-4b93-9dee-d0d06c8947a8.png)

So I updated my config to this:

```
let g:rainbow_conf = {
\	'guifgs': ['magenta', 'coral2', 'gold', 'deepskyblue', 'slateblue'],
\	'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
\	'guis': [''],
\	'cterms': [''],
\	'operators': '_,\|\.\|+\|-\|*\|\/\|%\|;\|=\|!\|<\|>_',
\	'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
\	'separately': {
\		'*': {},
\       'cpp': {
\           'parentheses_options': 'contains=@Comment',
\       },
\		'markdown': {
\			'parentheses_options': 'containedin=markdownCode contained',
\		},
\		'lisp': {
\			'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
\		},
\		'haskell': {
\			'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/\v\{\ze[^-]/ end=/}/ fold'],
\		},
\		'vim': {
\			'parentheses_options': 'containedin=vimFuncBody',
\		},
\		'perl': {
\			'syn_name_prefix': 'perlBlockFoldRainbow',
\		},
\		'stylus': {
\			'parentheses': ['start=/{/ end=/}/ fold contains=@colorableGroup'],
\		},
\       'nerdtree': 0,
\		'css': 0,
\	}
\}
```

But it has no effect

**Comment by luochen1990** [comment]
I cannot produce your issue, even without any extra rainbow configuration.

<img width="180" alt="image" src="https://user-images.githubusercontent.com/2309868/170412016-9660cd04-4594-4fa1-8c7b-a9e0cec6e094.png">

Have you enabled any 3rd-party syntax plugins for cpp?

**Comment by Curs3W4ll** [comment]
I tried on a newly installed machine (with docker), using neovim v0.5.1, but the comment colorization keep being broke in .cpp files
Only installed plugins are vimplug and the rainbow plugin.

The only configuration is the init.vim file containing the following:
```
call plug#begin()

Plug 'luochen1990/rainbow'

call plug#end()

hi Comment cterm=NONE ctermfg=red ctermbg=yellow

let g:rainbow_active = 1 " Load vim-rainbow for all the files

let g:rainbow_conf = {
\       'guifgs': ['magenta', 'coral2', 'gold', 'deepskyblue', 'slateblue'],
\       'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
\       'guis': [''],
\       'cterms': [''],
\       'operators': '_,\|\.\|+\|-\|*\|\/\|%\|;\|=\|!\|<\|>_',
\       'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
\       'separately': {
\               '*': {},
\               'markdown': {
\                       'parentheses_options': 'containedin=markdownCode contained',
\               },
\               'lisp': {
\                       'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
\               },
\               'haskell': {
\                       'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/\v\{\ze[^-]/ end=/}/ fold'],
\               },
\               'vim': {
\                       'parentheses_options': 'containedin=vimFuncBody',
\               },
\               'perl': {
\                       'syn_name_prefix': 'perlBlockFoldRainbow',
\               },
\               'stylus': {
\                       'parentheses': ['start=/{/ end=/}/ fold contains=@colorableGroup'],
\               },
\       'nerdtree': 0,
\               'css': 0,
\       }
\}
```
I changed comments highlight for better identification

**Comment by Curs3W4ll** [comment]
Try to play a bit with the operators, I found out that the only operator causing problems is the `/` one
If I switch my operators configuration to
```
\       'operators': '_,\|\.\|+\|-\|*\|%\|;\|=\|!\|<\|>_',
```
Comments colorization is no more broken

**Comment by Curs3W4ll** [comment]
Ok I don't know if this can help you, but I identify in which case the comment colorization get broke

An idea poped in my head when I found out that the problematic operator in cpp was `/`, so I think that this could be the 'comment identifier' (the character identifying a comment, `//` in c/cpp, `#` in bash/python, `"` in vim....) that was causing problems when it was in the operators

So I tested it, I added the `#` character in the operators list

And  that's it !
Without the `#` as an operator, python comment colorization is ok
![image](https://user-images.githubusercontent.com/72013831/170504372-6c295f7f-2af7-4136-a325-480aea2f3278.png)

But when I add the `#` character as an operator in the rainbow config, it then broke the comment colorization
![image](https://user-images.githubusercontent.com/72013831/170504522-eff40552-7854-41d6-841c-70fb3404d67b.png)

So the condition to broke comment colorization are
- Being inside a rainbow parentheses (`()`, `[]`, `{}`)
- Having the 'comment identifiers' of the language in the rainbow operators list

**Comment by Curs3W4ll** [comment]
Have you any idea of how can I fix it ?

**Comment by luochen1990** [comment]
I suggest just remove `/` from operators,  the operators feature is not designed for mathmatic operators, but for seperators of items in parentheses,  (maybe it should be called `seperators`)

**Comment by Curs3W4ll** [comment]
Alright thanks a lot !
