### ISSUE TITLE
[Bug] conflict with other plugin

### ISSUE THREAD

**Issue by Freed-Wu** [luochen1990/rainbow#186]
### **To Reproduce**

`test.bbcode`

```bbcode
I have 2 2560x1440 monitor:

[url=https://bbs.archlinux.org/]Arch Linux Forums[/url] 

[email]myname@example.com[/email] 
```

`test.vim`

```vim
#!/usr/bin/env -S vi -u
" $ uname -r
" 6.0.2-arch1-1
" $ has
" ✓ vi 0.8.0
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/luochen1990/rainbow
set runtimepath+=~/.local/share/nvim/repos/github.com/Winseven4lyf/vim-bbcode
let g:rainbow_active = 1
" $ chmod +x test.vim
" $ ./test.vim
```

## Actual

![Screenshot_20221027_220658](https://user-images.githubusercontent.com/32936898/198307991-0654e6cf-617c-4c4c-936f-1ef33636ed64.png)

## Expected

![Screenshot_20221027_220727](https://user-images.githubusercontent.com/32936898/198308017-9c18cdb3-3ec6-4ed8-8624-1fb35f5b2d96.png)

**Comment by luochen1990** [comment]
It seems like `rainbow` is not very useful in this case. You can disable `rainbow` for this filetype.

**Comment by Freed-Wu** [comment]
Ok. Is it a temporary solution, or the only solution we can do?

**Comment by luochen1990** [comment]
Dealing with syntax conflict need some knowledge about Vim's syntax highlighting mechanism, if you are not familier with it, then I suggest to disable `rainbow` plugin specificly for this filetype,  and this can be done in configuration, you can just see README and other issues to figure out how
