### ISSUE TITLE
Can we get rainbow parentheses inside string? in Any strings, like bash strings, or python strings or any other strings. I tried 'parentheses_options': 'containedin=strings contained',. But to no avail. I don't know if it's already possible to do or not, that's why I am putting it in feature request. 

### ISSUE THREAD

**Issue by s624** [luochen1990/rainbow#194]
Right now all the parentheses or braces inside strings get the color of the strings. But it's not hard to understand that these text are strings if everything except the braces/brackets/parentheses are having the text-highlights. 

I am not sure what solution I would like to have, but any solution would be good.

**Comment by luochen1990** [comment]
In most language, string have their own syntax highlighting, and it is defined in a high priority, so it is not possible to overlay it,  If you really want this,  you should disable the syntax rule for string literals and add your own one.

closing it until there are more specific suggestion.
