### ISSUE TITLE
[Bug] Colors not enabled with lazy.nvim

### ISSUE THREAD

**Issue by vehlwn** [luochen1990/rainbow#196]
### **Describe the bug**
With vim-plug this plugin worked well. But when I switched to lazy.nvim the plugin stopped working like it's ignoring `rainbow_active = 1`.

### **To Reproduce**

~/.config/nvim/init.lua:

```lua
-- Standard boilerplate from https://lazy.folke.io/installation
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
    if vim.v.shell_error ~= 0 then
        vim.api.nvim_echo({
            { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
            { out, "WarningMsg" },
            { "\nPress any key to exit..." },
        }, true, {})
        vim.fn.getchar()
        os.exit(1)
    end
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup("plugins")
```

~/.config/nvim/lua/plugins/rainbow.lua:

```lua
return {
    "luochen1990/rainbow",
    init = function()
        vim.g.rainbow_active = 1
        vim.g.rainbow_conf = {
            guifgs = {"Red", "Green", "Yellow"},
        }
    end
}
```

### **Expected behavior**

Parenthesis are highlighted as with vim-plug:

![Screenshot_20240801_184116](https://github.com/user-attachments/assets/62e277e5-8c56-49c8-af6d-d8458defbddf)

### **Screenshots**

Instead nothing is highlighted when opening a file and I have to manually call `:RainbowToggle` to activate plugin. Or workaround it with autocmd:

```lua
vim.api.nvim_create_autocmd("BufReadPost", {
    group = vim.api.nvim_create_augroup("ToggleRainbow", {}),
    callback = function()
        vim.cmd("RainbowToggle")
    end
})
```

![Screenshot_20240801_184125](https://github.com/user-attachments/assets/7c2a1ba8-9103-4734-b25f-83d3e73a848a)

### **Additional context**

- lazy.nvim version `077102c chore(main): release 11.14.1 (#1680) (7 days ago)`
- rainbow version `76ca1a2 fix: default config html tag issue #195 (5 days ago)`

**Comment by luochen1990** [comment]
Please report this to lazy.nvim , I don't think this plugin need some extra plugin to make it lazy, since the main part of this plugin is inside autoload/, which vim will lazy load it already.

**Comment by vehlwn** [comment]
OK. I'll reopen this issue there.
