### ISSUE TITLE
大佬要不要更新到 vim9script 啊

### ISSUE THREAD

**Issue by 1030504258** [luochen1990/rainbow#199]
大佬要不要更新到 vim9script 啊

**Comment by luochen1990** [comment]
1. vim9script 它兼容 Neovim 么？
2. 这个插件的代码逻辑主要是定义 Syntax规则，它本身没有什么运算负担，所以也不大可能从 vim9script 的优化中受益。

综上，切换到 vim9script 会损失兼容性， 且几乎没有什么收益。
