### ISSUE TITLE
[Bug] vim9.1使能rainbow时似乎和smartindent冲突

### ISSUE THREAD

**Issue by jiijkkk** [luochen1990/rainbow#201]
### **Describe the bug**
使用vim9.1代码+rainbow 3.3.1插件，并且配置set smartindent。在不使能rainbow时，撰写perl脚本，例如a.pl，在里面撰写一个简单的语句例如
`if($a){

  xxx;

}`
可以发现在另起一行写xxx时，它能够自动增加缩进，之后另起一行写}时，能够减小缩进。

然而在使能rainbow后，从{另起一行，不能自动增加缩进，第三行写}也不能自动减小缩进。

经试验仅启用rainbow一个插件即可复现

**Comment by jiijkkk** [comment]
哎。。我一般喜欢从release里面找一个稳定的，然而这个3.3.1竟然是2014年的release。master版本的没有bug。

**Comment by luochen1990** [comment]
因为大家基本都用插件管理工具管理vim插件了，所以release这个功能后面基本没怎么使用了
