### ISSUE TITLE
plugin breaks spell check in text files

### ISSUE THREAD

**Issue by Konfekt** [luochen1990/rainbow#24]
With `set spell` and `set spelllang=en`,  English mistakes are not recognized.

**Comment by curiousyogurt** [comment]
Confirmed; this plugin breaks some spellchecking.

**Comment by luochen1990** [comment]
which filetype ?  (`:set ft?`)

**Comment by Konfekt** [comment]
Over here it is Filetype text and the latest Github Version. On Linux, Vim 7.4.560.

**Comment by curiousyogurt** [comment]
Filetype = votl, using the VimOutliner plugin, here: https://github.com/vimoutliner/vimoutliner.  Spell checking works when the rainbow plugin.  The version of Vim is MacVim 7.4, with patches 1-258 applied (snapshot 73).  Any help would be appreciated.

**Comment by luochen1990** [comment]
when you toggled this plugin off, spell checking works again?

**Comment by curiousyogurt** [comment]
Yes, that is correct.  I just double-checked, and toggling the plugin off makes spellcheck work.  It is definitely the addition of rainbow that is stopping the spell checking in votl files.

**Comment by luochen1990** [comment]
is it fixed now ?

**Comment by Konfekt** [comment]
Seems fine to me, but better wait for@curiousyogurt 's confirmation.

**Comment by curiousyogurt** [comment]
Thank you for the fix!  Spellcheck now works with Votl files!

**Comment by luochen1990** [comment]
see #98
