### ISSUE TITLE
'*': 0 to disable for every filetype

### ISSUE THREAD

**Issue by Grahack** [luochen1990/rainbow#26]
Hi, thanks for *rainbow*.
I'm using it only for lisp-like languages. I know I can disable any type using `'the_type': 0`, but would it be possible to just use `'*': 0` for disabling everything, and leave a `'lisp': {}` to let *rainbow* work for lisp-like languages ?

**Comment by luochen1990** [comment]
you are right, this should be supported. wait a minute!

**Comment by luochen1990** [comment]
have a try now!

**Comment by Grahack** [comment]
It works great, thanks.
