### ISSUE TITLE
Rainbow doesn't highlight Javascript closures

### ISSUE THREAD

**Issue by tupton** [luochen1990/rainbow#28]
![screenshot 2015-02-06 14 28 33](https://cloud.githubusercontent.com/assets/47334/6087053/7277f584-ae0c-11e4-89c5-8c8e31e98943.png)

This makes it a little less useful when using AMD modules, where your entire file is wrapped in a `require` call with a callback as an argument.

**Comment by luochen1990** [comment]
I don't have this problem here with the default javascirpt syntax configuration. Did you used some other  syntax plugins for javascript ?

**Comment by tupton** [comment]
> Did you used some other syntax plugins for javascript ?

Ah, yes, that seems to be the culprit. I'm using https://github.com/pangloss/vim-javascript and something there seems to be inhibiting rainbow in that situation.

I'll look into it further and see if I can figure out why. Thanks for taking a look!

**Comment by tupton** [comment]
For anyone that uses pangloss/vim-javascript, it seems that https://github.com/jelera/vim-javascript-syntax is more up-to-date and is compatible with rainbow.
