### ISSUE TITLE
Plugin breaks neco-ghc

### ISSUE THREAD

**Issue by dkasak** [luochen1990/rainbow#29]
This plugin partially breaks [neco-ghc](https://github.com/eagletmt/neco-ghc/) which is a completion plugin for Haskell. The problem seems to be that rainbow fiddles with the syntax IDs (as returned by synIDattr()) which breaks the completion engine in some circumstances. Specifically, when completing language pragma directives which look like this:

```
{-# LANGUAGE OverloadedStrings #-}
```

This is a comment in Haskell (with a special metaformat because it's also a compiler pragma directive) and neco-ghc expects `synIDAttr` to return `hsPragma` here, but with rainbow turned on it returns `rainbow_r0` (I'm guessing because it contains braces).

I'm not sure if this is fixable or even worth fixing, since it works if you disable this plugin on braces for Haskell (and braces are used sparingly there), but I thought I'd let you and others know, in case someone has a similar problem. Feel free to close the issue if there is nothing to be done.

**Comment by luochen1990** [comment]
yeah, it's right for you to tell us about this problem. actually, you can solve this problem via an advanced configuration of rainbow: you can decide which kinds of parentheses to use for haskell files, see the README for more infomation, good luck!

**Comment by dkasak** [comment]
Yeah, that's what I meant by my last paragraph and that's exactly what I did. Thanks for the advice!

**Comment by thejohnfreeman** [comment]
Do you mind sharing your configuration, @dkasak ?

**Comment by dkasak** [comment]
@thejohnfreeman, I don't use this plugin anymore, but I copied the [example configuration](https://github.com/luochen1990/rainbow#user-content-configure) and added something like the following to the `separately` list:

    \       'haskell': {
    \           'parentheses': [['(',')'], ['\[','\]']],
    \       },

**Comment by luochen1990** [comment]
Actually, If you are familiar with regular expression in vim,  you can do it better via zero width match to precisely skip the pragma braces :)

**Comment by dkasak** [comment]
@luochen1990 Perhaps this could be added as a special case for filetype haskell in the default configuration then?
