### ISSUE TITLE
Uh oh... yet another spell checking problem

### ISSUE THREAD

**Issue by mwnx** [luochen1990/rainbow#30]
Well, here's a new one...

The latest commit –which fixes a problem with spell checking and plain text files– introduces a new bug where the `@Spell` syntax environments are messed up or something like that.

Specifically, in C files, variable names (outside comments) are now being highlighted when they shouldn't be.

It would seem that a simple fix for this is removing `,@NoSpell` part of line 82 altogether:

    -	let def_rg = 'syn region %s matchgroup=%s containedin=%s contains=%s,@NoSpell %s'
    +	let def_rg = 'syn region %s matchgroup=%s containedin=%s contains=%s %s'

I'm not quite sure what problem it was supposed to solve in the first place but I'm not seeing any new problem yet.

**Comment by luochen1990** [comment]
I should say, spell checking is evil ..
why you need spell checking when coding ??
what you need is syntax checking, not spell checking. just `:set nospell` for code types, you can use an autocmd command to do this.

I want to solve all this , but vim's implementation makes it impossible ...  if there is any way, just tell me.

**Comment by mwnx** [comment]
I'd like spell checking to avoid making spelling mistakes in comments, or so that I can detect them and correct them.

I haven't noticed any problems with the modification I proposed yet. So... maybe it could work... And it has the conceptually nice feature of getting rid of any spell checking reference in Rainbow's code.

**Comment by luochen1990** [comment]
#24

**Comment by mwnx** [comment]
The fix I am proposing does not reintroduce the problem in #24 nor does it seem to cause any  problems when editing tex files (#17).

**Comment by boris-petrov** [comment]
Hello, this is still a problem. I am getting the issue for Python files but it seems to only be highlighting wrongly written words when they are in parentheses... @luochen1990 - some of us like the spellchecking even when writing code. Please try to fix that. I have a fork of [kien's rainbow parentheses](https://github.com/boris-petrov/rainbow_parentheses.vim) that try to fix the same problems there and the fix seems to do exactly what I want. You can try applying something like that to your own project.

**Comment by haifengkao** [comment]
@mwnx is correct. It doesn't reintroduce the problem for objc files.

**Comment by luochen1990** [comment]
see #98
