### ISSUE TITLE
Does not work with neovim

### ISSUE THREAD

**Issue by gonzaloserrano** [luochen1990/rainbow#31]
Hi,

Not sure why but the plugin does not work with neovim, have you tried it by chance?

Regards,

**Comment by luochen1990** [comment]
I'm sorry that I dont use neovim. can I have a look at the error message?

**Comment by gonzaloserrano** [comment]
There is no error message but it's just that it does not work. Probably i will report it to the neovim project but i wondered if you tried it already.

Thanks anyway!

**Comment by gambledor** [comment]
Here below the errors I get when I enable the plugin in neovim
![rainbowerror](https://cloud.githubusercontent.com/assets/649036/8953988/d636a2b0-35e2-11e5-827e-b4f364eb82ea.png)

**Comment by luan** [comment]
I don't think this is a problem with the `rainbow` plugin necessarily. Neovim seems to not work with the named colors of the example, i.e. "royalblue3", it's easy enough to fix by just using a hex value such as this:

```vim
let g:rainbow_conf = {
    \   'guifgs': ['#f92672', '#a6e22e', '#f4bf75', '#66d9ef', '#ae81ff', '#a1efe4'],
    \   'ctermfgs': 'xterm-256color' == $TERM || 'screen-256color' == $TERM ? ['1', '2', '3', '4', '5', '6', '7'] : ['lightblue', 'lightgreen', 'yellow', 'red', 'magenta'],
    \   'operators': '_,_',
    \   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
    \   'separately': {
    \       '*': {},
    \       'tex': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
    \       },
    \       'vim': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
    \       },
    \       'html': {
    \           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
    \       },
    \       'css': 0,
    \   }
    \}
```

**Comment by luochen1990** [comment]
I think maybe you should submit an issue to neovim.

**Comment by luan** [comment]
By the way, I tried removing this line: https://github.com/luochen1990/rainbow/blob/master/plugin/rainbow.vim#L111 and it seems to be working just fine on both regular vim and neovim (have been using it like that for the past 3 days or so at work). Can't really find the reason for that to be there anyway.

Thoughts? I'd send a PR removing the line but I don't know if that's there for some other obscure reason I haven't thought of.

@luochen1990

**Comment by gonzaloserrano** [comment]
Nice one @luan :)

**Comment by gonzaloserrano** [comment]
In the end it did not work for me so i'm using https://github.com/junegunn/rainbow_parentheses.vim instead

**Comment by dan-santana** [comment]
I was having the same problem after adding `neomake` to my setup. Here are the steps to reproduce the bug:

```
" To create a location list
:lexpr []

" Open the location list
:lopen

" Go back to the main window
<c-w>j

" Create a location list again. *The bug happens in this step*
:lexpr []
```

I didn't investigate any further, but as far as I know `hi clear ...` prevailed over `syn match/region ...`, and by removing the `rainbow#hide()` call in `rainbow#clear()` (as @luan noted) it worked fine.

@luochen1990 is there any reason for using both `hi clear ...` and `syn clear ...` in `rainbow#clear()`? If there is, would you accept a PR for conditionally looking if it's running in Neovim?
