### ISSUE TITLE
Conflicts with syntax regions within ()

### ISSUE THREAD

**Issue by jeaye** [luochen1990/rainbow#32]
When creating the syntax file for a Lisp I'm developing, I found that `rainbow` prevents this to be highlighted as a comment properly. Example VimL:

```viml
syntax region commie start="(;" end=";)"
highlight link commie Comment
```

The following should then be considered a comment:

```text
(; foo ;)
```

After disabling this plugin, everything works as expected.

**Comment by luochen1990** [comment]
oh，right，this is a mistake but can be solved in minutes.

**Comment by luochen1990** [comment]
You can add these to your vimrc, but, you will then find that Vim's default syntax file for lisp doesn't treat this usage as well. It didn't eat the start parenthes of `(; ... ;)`....
```
let s:rainbow_conf = {
\	'separately': {
\		'lisp': {
\			'parentheses': ['start=/(\ze[^;]/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
\			'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
\		},
\	}
\}
```

**Comment by jeaye** [comment]
On Fri, May 29, 2015 at 08:02:01PM -0700, Luo Chen wrote:
>    You can add these to your vimrc, but, you will then find that Vim's
>    default syntax file for lisp doesn't treat this usage as well. It didn't
>    eat the start parenthes of (; ... ;)....

Thanks. My syntax file isn't based on the stock lisp, so hopefully this won't have any issues.

**Comment by jeaye** [comment]
Verified, this is working properly for my syntax file now. Thanks for the workaround! If there are no changes you'd like to make to `rainbow` for this, we can close this ticket.

**Comment by luochen1990** [comment]
I'm not sure that I should add these to rainbow's default configuration.  Since the default syntax file for lisp doesn't support it .

**Comment by jeaye** [comment]
On Fri, May 29, 2015 at 08:13:51PM -0700, Luo Chen wrote:
>    I'm not sure that I should add these to rainbow's default configuration.
>    Since the default syntax file for lisp doesn't support it .

Makes sense to me; let's close this guy. Thanks again.

**Comment by luochen1990** [comment]
I wonder is this comment style widely supported by lisp compilers ?

**Comment by jeaye** [comment]
On Fri, May 29, 2015 at 08:31:30PM -0700, Luo Chen wrote:
>    I wonder is this comment style widely supported by lisp compilers ?

No. As I said initially, it's for my own lisp. That is, it's a language which I'm developing which is a lisp but is different from all other lisps: https://github.com/jeaye/jank
