### ISSUE TITLE
Reloading vimrc deactivates rainbow highlighting

### ISSUE THREAD

**Issue by beyondmarc** [luochen1990/rainbow#33]
Hi luochen1990,

I have the plugin always enabled by setting `g:rainbow_active:1` in my .vimrc. That works fine except when calling `:so ~/.vimrc`. It then removes the parentheses highlighting but somehow it appears that the plugin is still active since, to get them highlighted again I need to call `RainbowToggle` twice.

I have the same problem when calling `vim -c "~/.vimrc_alt"` to use a different vim config file.

I tried to figure out what's wrong, but I couldn't.

BTW, very cool plugin! I love it!

Thanks!

**Comment by luochen1990** [comment]
`source ~/.vimrc` seems not a safe way. but maybe I should add the `RainbowToggleOn` and `RainbowToggleOff` commands so that you can put it on your vimrc and when you source you vimrc they will be executed automaticly.  what do you think about this?

**Comment by beyondmarc** [comment]
I think that's a very good idea! Thank you!

**Comment by luochen1990** [comment]
you can add `if exists(':RainbowToggleOn') | RainbowToggleOn | endif` to your vimrc now.

**Comment by beyondmarc** [comment]
I needed a small modification: `if exists(':RainbowToggleOn') | exe "RainbowToggleOn" | endif`. After that, it worked perfectly!

Thank you!
