### ISSUE TITLE
Advance configuration to match vim-niji's colors

### ISSUE THREAD

**Issue by Happy-Dude** [luochen1990/rainbow#35]
Hi! Just found this plugin, and it looks super awesome.
Previously I was using amdt's niji plugin for rainbow parentheses, but he longer is maintaining it due to time constraints.

One thing I love is niji's highlighting colors, and I would love to replicate that in rainbow. But unfortunately, I couldn't figure out how to make a advance configuration to get it right. (I tried looking at #1, but I still couldn't figure it out.) 

Can someone help me out?

As a reference, here is a vim-niji repository clone, https://github.com/raymond-w-ko/vim-niji, and I think the relevant highlight file: https://github.com/raymond-w-ko/vim-niji/blob/master/autoload/niji.vim

Thanks; I appreciate any help I get!

**Comment by luochen1990** [comment]
Add things below to your vimrc and modify the colors to what you want:

```
let g:rainbow_conf = {
\   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
\   'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta']
\}

**Comment by Happy-Dude** [comment]
Just an update, I came up with the following for my config:
```viml
let g:rainbow_conf = {
\   'guifgs'     : ['#FE2712', '#66B032', '#0392CE', '#FD5308', '#0247FE', '#FB9902', '#8601AF', '#FEFE33', '#A7194B', '#D0EA2B'],
\   'ctermfgs'   : ['1', '2', '3', '4', '5', '6', '7', '9', '10', '11' ,'12', '13', '14', '15'],
\   'separately' : {
\       '*'   : {
\               'guifgs'     : ['#FE2712', '#66B032', '#0392CE', '#FD5308', '#0247FE', '#FB9902', '#8601AF', '#FEFE33', '#A7194B', '#D0EA2B'],
\               'ctermfgs'   : ['1', '2', '3', '4', '5', '6', '7', '9', '10', '11' ,'12', '13', '14', '15'],
\       },
\       'lisp': {
\               'guifgs'     : ['#FE2712', '#66B032', '#0392CE', '#FD5308', '#0247FE', '#FB9902', '#8601AF', '#FEFE33', '#A7194B', '#D0EA2B'],
\               'ctermfgs'   : ['1', '2', '3', '4', '5', '6', '7', '9', '10', '11' ,'12', '13', '14', '15'],
\       },
\       'tex'  : {
\           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
\       },
\       'vim'  : {
\           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
\       },
\       'xml'  : {
\           'parentheses': ['start=/\v\<\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'))?)*\>/ end=#</\z1># fold'],
\       },
\       'xhtml': {
\           'parentheses': ['start=/\v\<\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'))?)*\>/ end=#</\z1># fold'],
\       },
\       'html' : {
\           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
\       },
\       'php'  : {
\           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold', 'start=/(/ end=/)/ containedin=@htmlPreproc contains=@phpClTop', 'start=/\[/ end=/\]/ containedin=@htmlPreproc contains=@phpClTop', 'start=/{/ end=/}/ containedin=@htmlPreproc contains=@phpClTop'],
\       },
\       'css'  : 0
\   }
\}
```

Closing issue; thanks for the help!

**Comment by luochen1990** [comment]
Actually, you can simply ignore the configuration about `separately.tex`, `separately.vim` etc. to use the default configuration.  : )

**Comment by Happy-Dude** [comment]
Unfortunately, I found that unless I overwrote some of the settings, my changed "default" settings wouldn't take effect.
For example, when I had a default config and I didn't overwrite the tex config, it used the tex config from rainbow's default settings.
Would this happen to be a bug?

**Comment by luochen1990** [comment]
I'm not sure what's the problem for you, but these just works for me :)
```
	let g:rainbow_conf = {
	\   'guifgs': ['royalblue3', 'darkorange3'],
	\}
```

**Comment by Happy-Dude** [comment]
@luochen1990, did you try using your default config for Lisp code? If I don't overwrite it, the default one from https://github.com/luochen1990/rainbow/blob/master/plugin/rainbow.vim gets used. I see this in both ctermfgs and guifgs.

**Comment by luochen1990** [comment]
@Happy-Dude lisp is the only one which `guifgs` is specified by the default config (since lisper need more colors for parentheses I think...
