### ISSUE TITLE
Doesn't work with neovims true color mode

### ISSUE THREAD

**Issue by hoschi** [luochen1990/rainbow#36]
Normal vim and nvim work as expected. When I enable neovims true color mode with `NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim` it doesn't. junegunn/rainbow_parentheses.vim version works, but has no operator highlighting :(

**Comment by gonzaloserrano** [comment]
Same thing here.

**Comment by luochen1990** [comment]
I'm sorry to hear that, but I don't use neovim...  if it is a problem caused by true color mode, maybe you can try to change the color used via rainbow's configuration.  If this doesn't work, maybe you should feedback this problem to neovim's developer. I'll appreciate it if you found a solution and feedback it to me here :)

**Comment by gf3** [comment]
any luck here?

**Comment by hoschi** [comment]
Afaik true color mode uses the gui color values, but this plugin works in normal GVim. All other plugins/settings work out of the box with true color mode when they are configured for GVim. This makes hard for me to get an idea where the bug could be. Said all that, I hadn't time yet to 'debug' it :(

**Comment by luochen1990** [comment]
It may be helpful if I can have a glance at the error messages thrown by neovim :)

**Comment by hoschi** [comment]
There is no error message, at least no one I saw. Its just not colored.
@gf3 @gonzaloserrano scream if you get one ;)

**Comment by hoschi** [comment]
Here is my config, I tried to use basic gui colors:
```
let g:rainbow_active = 1
let g:rainbow_conf = {
\   'guifgs': ['red', 'green', 'cyan', 'magenta'],
\   'ctermfgs': ['darkblue', 'darkmagenta', 'darkcyan', 'darkred', 'darkgreen'],
\   'operators': '_,_',
\   'parentheses': [['(',')'], ['\[','\]'], ['{','}']],
\   'separately': {
\       '*': {},
\       'lisp': {
\           'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
\           'ctermfgs': ['darkgray', 'darkblue', 'darkmagenta', 'darkcyan', 'darkred', 'darkgreen'],
\       },
\       'html': {
\           'parentheses': [['(',')'], ['\[','\]'], ['{','}']],
\       },
\       'javascript': {
\           'parentheses': [['(',')'], ['\[','\]'], ['{','}']],
\           'operators': '_,\|!\|>\|<\|>=\|<=\|===\|!==\|!=\|==\|&&\||_',
\       },
\       'tex': {
\           'operators': '',
\           'parentheses': [['(',')'], ['\[','\]']],
\       },
\   }
\}
```

vim-plug says the plugin is loaded, also I have the `:RainbowToggle` command (which does nothing). I tested it with a `test.txt` and a `test.js` file, no colors in either file.

**Comment by gf3** [comment]
btw https://github.com/junegunn/rainbow_parentheses.vim works perfectly in neovim

**Comment by hoschi** [comment]
Here also, as I said in my first comment.

**Comment by luochen1990** [comment]
I had merged #38 and hope this problem had been solved. Any one chould help to confirm this?

**Comment by eshansingh** [comment]
Can confirm for me, don't know about OP though.

**Comment by hoschi** [comment]
Sorry, I hope to check this on holidays.

**Comment by eshansingh** [comment]
News?

**Comment by hoschi** [comment]
It works, thank you :)
