### ISSUE TITLE
linux 下目录位置有些不同

### ISSUE THREAD

**Issue by dubuyuye** [luochen1990/rainbow#37]
我的系统为`archlinux`，vim版本为7.4，按照说明文档放置插件与配置未生效。
但是把`rainbow.vim`放到`/usr/share/vim/vim74/plugin`下，并且将所有配置写到`/etc/vimrc`下就生效了。

**Comment by luochen1990** [comment]
各系统的vim配置文件的位置的确有差异，谢谢指出。
