### ISSUE TITLE
Plugin breaks vim-color-css

### ISSUE THREAD

**Issue by crivotz** [luochen1990/rainbow#40]
This plugin breaks [vim-color-css](https://github.com/ap/vim-css-color) which is a preview plugin for hex color in css file.

Thanks

**Comment by luochen1990** [comment]
I think you should just disable this plugin for css particularly. since nested parentheses will never appears in css files.

**Comment by luochen1990** [comment]
see here https://github.com/luochen1990/rainbow/issues/14 for more details

**Comment by crivotz** [comment]
Thanks for the reply.
Unfortunately it does not solve my problem, highlight color also happens in other file formats

I solved it by assigning a shortcut to toggle function

**Comment by luochen1990** [comment]
Try this one please.
···
	let g:rainbow_conf = {
	\	'separately': {
	\		'css': {
	\			'parentheses': ['start=/{/ end=/}/ fold contains=@colorableGroup'],
	\		},
	\	}
	\}
···

**Comment by crivotz** [comment]
It's works.
Thanks
