### ISSUE TITLE
Enable only for certain filetypes?

### ISSUE THREAD

**Issue by for-coursera** [luochen1990/rainbow#43]
Is it possible to enable rainbow only for certain filetypes (described in `separately` key) and, consequently, disable for everything else?

**Comment by luochen1990** [comment]
Yes, it's easy to do that, just add '*': 0 to disable rainbow for other files. The configuration below demos how to enable rainbow only for c++ files.

```
	let g:rainbow_conf = {
	\	'separately': {
	\		'*': 0,
	\		'c++': {}
	\	}
	\}
```

**Comment by for-coursera** [comment]
Thanks a lot!

**Comment by luochen1990** [comment]
If you had confirmed that it works, please close this issue to let me know, thx.
