### ISSUE TITLE
light colorscheme

### ISSUE THREAD

**Issue by peidong** [luochen1990/rainbow#45]
There is an issue that when we use light colortheme, the brackets are not recognizable.
Here is my code for solving this. [my code link](https://github.com/peidong/vimrc/blob/master/vimrc#L409-L456)

Could you add a "if" to recognize dark theme or light theme?
Thank you!

**Comment by luochen1990** [comment]
You really doesn't need to do so. You can only specify the config part that you wan't to change, and keep other items empty. ie:
```
let lightcolors =  ['lightblue', 'lightyellow', 'red', 'darkgreen', 'darkyellow', 'lightred', 'yellow', 'cyan', 'magenta', 'white']
let darkcolors = ['DarkBlue', 'Magenta', 'Black', 'Red', 'DarkGray', 'DarkGreen', 'DarkYellow']
let g:rainbow_conf = {
\   'ctermfgs': (rainbow_background == "light"? darkcolors : lightcolors)
\}
```

**Comment by peidong** [comment]
@luochen1990 Thank you very much. And I have a question. I use iTerm2 with 256-color support. However, the ctermfgs color only supports 16 colors. How can I use 256 colors in the rainbow's ctermfgs color?
Thank you!

**Comment by luochen1990** [comment]
this may help you: https://github.com/luochen1990/rainbow/issues/1

**Comment by guanjianzhe** [comment]
I really need to solve this problem

I have copy your code into my .vimrc, but just come out:

E121: Undefined variable: background
E15: Invalid expression: {   'ctermfgs': (background=="light"? darkcolors : lightcolors)}

I need your help, thank you. why did't put you code into your plugin derectly??

**Comment by peidong** [comment]
@guanjianzhe You can refer this [link](https://github.com/peidong/pei-vim/blob/master/vimrc/.vimrc#L920-L937).

And that is because the color is not defined in 'ctermfgs'.

**Comment by guanjianzhe** [comment]
but it can work:
            let g:rainbow_conf = { 
                        \   'ctermfgs': ('light'=='light' ? darkcolors : lightcolors)
                        \}   

did I have defined "rainbow_background"?

**Comment by guanjianzhe** [comment]
E121: Undefined variable: rainbow_background
E15: Invalid expression: {   'ctermfgs': (rainbow_background=='light' ? darkcolors : lightcolors)}

**Comment by peidong** [comment]
you don't need to do so
On 周一, 4月 18, 2016 at 21:00, guanjianzhe <notifications@github.com> wrote:
E121: Undefined variable: rainbow_background
E15: Invalid expression: { 'ctermfgs': (rainbow_background=='light' ? darkcolors : lightcolors)}

**Comment by guanjianzhe** [comment]
sorry, I can't understand what you say, could you   describe more specifically what should I do?

**Comment by peidong** [comment]
@guanjianzhe You don't need to define rainbow_background which is set for my own use.And you can just replace rainbow_background with "light" or "dark". Or you could do `let rainbow_background="light"`.

Hope this helps you.

**Comment by guanjianzhe** [comment]
I want to judge background is light or dark.how could I fix this:

    'ctermfgs': ( background == "light"? darkcolors : lightcolors)

**Comment by guanjianzhe** [comment]
I think this problem is too easy to figure it out. this code had verified and I think should merge into master branch as a new basic features：

            let lightcolors =  ['lightblue', 'lightyellow', 'red', 'darkgreen', 'darkyellow', 'lightred', 'yellow', 'cyan', 'magenta', 'white']
            let darkcolors = ['DarkBlue', 'Magenta', 'Black', 'Red', 'DarkGray', 'DarkGreen', 'DarkYellow']
            let g:rainbow_conf = {
                        \   'ctermfgs': (&background=="light"? darkcolors : lightcolors)
                        \}

**Comment by luochen1990** [comment]
@guanjianzhe I don't think so, this is only a configuration people may need, and it can be done via the configuration. the only thing that needed is a little vim script knowledge: the conditional statement `p ? a : b`, there is no threshold for any hacker.

**Comment by guanjianzhe** [comment]
@luochen1990 Absolutely understand what you say,  thank you.
