### ISSUE TITLE
sass file conflict with vim theme 

### ISSUE THREAD

**Issue by mydearxym** [luochen1990/rainbow#47]
love your work , but there is issue in scss file 

before:
![before](https://cloud.githubusercontent.com/assets/6184465/11985560/0558f240-aa01-11e5-812e-1d6dc11dc352.png)

after: 
![after](https://cloud.githubusercontent.com/assets/6184465/11985565/0db8ba4c-aa01-11e5-888a-57d9c16ad2e3.png)

**Comment by luochen1990** [comment]
these may help: https://github.com/luochen1990/rainbow/issues/14 https://github.com/luochen1990/rainbow/issues/40

**Comment by mydearxym** [comment]
thanks for reply 
i solve the problem by install [vim-haml](https://github.com/tpope/vim-haml)
but i don't know why ...
