### ISSUE TITLE
Disabling folding in configuration doesn't seem to work

### ISSUE THREAD

**Issue by theodelrieu** [luochen1990/rainbow#48]
Hi, there seems to be a problem with folding, especially with multi-line expressions.

No folding involved:

```
void foo(int a, int b)
{
}
```

Whereas the next two lines are folded:

```
void some_long_function(long_param p1,
                                          long_param p2)
{
}
```

Same thing when I tried to configure rainbow in my vimrc, I surely did something wrong:

```
let g:rainbow_conf = {'separately': 
                                      {'vim':
                                             {'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/'],},
                                      }
                                  }
```

Thanks !

**Comment by luochen1990** [comment]
what do you get when `:set foldmethod?`

**Comment by theodelrieu** [comment]
I get : manual.
I use the plugin Fastfold, I tried to remove it to see if it clashed with rainbow, but it had no effect.

**Comment by luochen1990** [comment]
the configuration of rainbow about folding only works when foldmethod is `manual`

**Comment by theodelrieu** [comment]
Thanks for your reply, I've put this line in my vimrc: 
> set foldmethod=syntax

However, it doesn't change anything. The output of :set foldmethod gives me 'syntax' each time now.
Is there something in my configuration that needs to be changed ?
