### ISSUE TITLE
Manual Install doesn't work

### ISSUE THREAD

**Issue by CrazySyntax** [luochen1990/rainbow#51]
I did exactly what the manual installation says. I copied the file rainbow.vim to ~/.vim/plugin and added the sentence:

`let g:rainbow_active = 1
to .vimrc file. However, when I try to source the .vimrc file, I get an error:

> syntax: command not found bash: let: g:rainbow_conf: syntax error in expression (error token is ":rainbow_conf")

Do you have an idea how to solve this problem?

BTW, I didn't install Vundle. That's why I used the manual installation.

**Comment by luochen1990** [comment]
I noticed that the error message you offered is talking about `g:rainbow_conf`, can you tell me more about this ?

**Comment by merwok** [comment]
This error message comes from a *bash* source command, not a vim command.

**Comment by luochen1990** [comment]
The error message implies that the vim-script sentence `let g:rainbow_conf ...` is treated as an bash command.

I need more detail about your operation steps to figure out what happend. Is there anybody who can provide a full operation list?

**Comment by luochen1990** [comment]
seems not a common problem, closed now.
