### ISSUE TITLE
It does not work with janus 

### ISSUE THREAD

**Issue by casertap** [luochen1990/rainbow#52]
https://github.com/carlhuda/janus

I put the rainbow.vim in the .janus folder and added let g:rainbow_active = 1 in my .vimrc.after but It does not work.

I do not even have access to :RainbowToggle

**Comment by balsagoth** [comment]
Did you find a way?

**Comment by luochen1990** [comment]
I'm not familier with the janus project, if anyone can help, please.

PS: maybe you can submit this issue to janus to see if anyone can help.
