### ISSUE TITLE
RainbowToggleOn results in errors on non-standard file loads

### ISSUE THREAD

**Issue by cmcginty** [luochen1990/rainbow#53]
I have a `autocmd` to enable rainbow toggle with `RainbowToggleOn` on all my files when the buffer is enabled. This usually works when loading files with CtrlP, NerdTree, or the command line, but I've come across some edge cases where a large amount of errors get dumped to the screen during the `autocmd`. Right now it happens when I load a new file with vim-fugitve `:Gedit`.

After more testing, the errors go away in the buffer after I call `RainbowToggle`. I wonder if there is some initialization code that is only run during `RainbowToggle` that is being bypassed when only `RainbowToggleOn` in called.

**Comment by yous** [comment]
Yes, `RainbowToggleOn` assumes the existence of `b:rainbow_conf`. #50 may fix this.
