### ISSUE TITLE
Colors disappear after reloading vimrc.

### ISSUE THREAD

**Issue by hit02** [luochen1990/rainbow#54]
Calling the command ":so $MYVIMRC" restore standard colors.
Calling then 2 times ":RainbowToggle" returns rainbow colors.
I tested this on Windows 7 for C++ and PHP.

**Comment by HaleTom** [comment]
Does putting `call rainbow#load()` at the bottom of your `vimrc` help?

**Comment by hit02** [comment]
Yes, it helped.

**Comment by sagi** [comment]
### Fix for more recent versions:

For those who experience it today, add the following to the end of your `.vimrc`:
~~~vim
call rainbow_main#load()
~~~

### Why it works? 
Nowadays, the `load()` method is present at the `rainbow/autoload/rainbow_main.vim` file.
