### ISSUE TITLE
Plugin should work even without  g:rainbow_active not set

### ISSUE THREAD

**Issue by sergei-dyshel** [luochen1990/rainbow#56]
Currently one needs to define `g:rainbow_active = 0/1` in order for plugin to work (commands to be available).
IMHO, that's not normal.

**Comment by SethArchambault** [comment]
Agree, this was pretty confusing!

**Comment by luochen1990** [comment]
This is a design choice, by this design, people can feel free to install rainbow into global vim directory in a multi-user os, and each people can decide whether to enable rainbow themselves.

And in the future, rainbow is designed to enpower other syntax plugin developers to develop their own plugins, and  the rainbow plugin itself will be installed as a dependency, at most of the time, you don't need to active it.
