### ISSUE TITLE
[req] Support combined filetypes

### ISSUE THREAD

**Issue by HiPhish** [luochen1990/rainbow#61]
Combined filetypes are types that have one or more dots in them. `:h filetype` gives the following explanation:

> When a dot appears in the value then this separates two filetype names.  Example:
> 
> ```
> /* vim: set filetype=c.doxygen : */ ~
> ```
> 
> This will use the "c" filetype first, then the "doxygen" filetype.    This works both for filetype plugins and for syntax files.  More than one dot may appear.

I am using the HTML template-engine Jinja for websites and the filetype should be set to `html.jinja`, i.e. first apply settings by HTML, then the Jinja settings (current plugins don't do that, but I was considering doing my own). Here is the Jinja website with a code sample:

```
{% extends "layout.html" %}
{% block body %}
  <ul>
  {% for user in users %}
    <li><a href="{{ user.url }}">{{ user.username }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}
```

http://jinja.pocoo.org/

However, when I set the file type to `html.jinja` I lose the rainbow feature. I have to add a new entry called `html.jinja` and then copy-paste the settings for HTML and Jinja into that new setting. What I would like would be if the two could somehow be combined automatically, first apply HTML and then Jinja. If there are no Jinja settings only apply the HTML ones, and if there are no HTML settings only apply the Jinja ones.

**Comment by HiPhish** [comment]
Another thing I noticed, doing this:
```
let g:rainbow_conf['html.jinja'] = g:rainbow_conf['html']
```
won't work:

> Error detected while processing /Users/hiphish/.config/nvim/plugin/rainbox.vim:
> line   33:
> E716: Key not present in Dictionary: html
> E15: Invalid expression: g:rainbow_conf['html']

Moving the code to the `init.vim` (Neovim) or `vimrc` (Vim) throws the same error. Otherwise I could have used that to break up a compound file type and compose the settings out of the individual pieces.

Next I tried copy-pasting the settings, it compiled, but it didn't colour the tags:
```
let g:rainbow_conf['html.jinja'] = {'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],}
```

The only thing that had an effect as copy-pasting settings in the dictionary literal itself. Modifying the dictionary does not yield any results, even if the modification just below the initialisation.

**Comment by HiPhish** [comment]
I got it working. It's small change, in `rainbow#hook()` we modify how `b_conf` gets its value. The original way is pretty simple: see if there are setting for that file type, and if there are then copy them over, otherwise copy over the generic ones.

My change first splits the file type along the `.` characters and loops over the resulting list. For each type we first see if there are setting for that type, and if there are we merge the settings together. I'm not going to issue a pull request because I don't know if you like the idea even in the first place, so here is the raw quick&dirty patch first:

```
diff --git a/plugin/rainbow.vim b/plugin/rainbow.vim
index 3463ea5..c70e7f3 100644
--- a/plugin/rainbow.vim
+++ b/plugin/rainbow.vim
@@ -163,7 +163,34 @@ func rainbow#hook()
 	else
 		let separately = extend(copy(s:rainbow_conf.separately), exists('g:rainbow_conf.separately')? g:rainbow_conf.separately : {})
 	endif
-	let b_conf = has_key(separately, &ft)? separately[&ft] : separately['*']
+
+	" Handle compound filetypes (the ones with a dot) by breaking the string
+	" into a list and looping over the items. See :h 'ft' for this kind of
+	" filetype.
+	let b_conf = {}
+	for ft in split(&filetype, '\v\.')
+		if !has_key(separately, ft)
+			continue
+		endif
+		let entry = separately[ft]
+		" We merge the settings for all file types into one. If the key is
+		" already in b_conf merge the settings, otherwise add a new item.
+		for [key, value] in items(entry)
+			if has_key(b_conf, key)
+				if type(value) == type([])
+					let b_conf[key] += value
+				else
+					let b_conf[key] .= value
+				endif
+			else
+				let b_conf[key] = value
+			endif
+		endfor
+	endfor
+	if empty(b_conf)
+		let b_conf = separately['*']
+	endif
+
 	if type(b_conf) == type({})
 		let b:rainbow_conf = extend(g_conf, b_conf)
 		call rainbow#load()
```

The one setting that can be a problem is `operators`, I am concatenating them for now, but that's not the right thing to do obviously. In #62 I have proposed a new feature which would also make merging operator settings easier. Please let me know what you think, I believe support for compound data types would be a great feature.

**Comment by luochen1990** [comment]
I think this is a good idea!  looking forward for a pr   ↖(^ω^)↗

**Comment by HiPhish** [comment]
I'll get to it in the next couple of days :)

**Comment by luochen1990** [comment]
This feature is supported finally: https://github.com/luochen1990/rainbow/commit/3c3f4daed222f108b1b4d50bbf0d8abdf0b5f618

@HiPhish  Thanks for your smart idea and your contribution.
