### ISSUE TITLE
[req] Add "between" to start and end

### ISSUE THREAD

**Issue by HiPhish** [luochen1990/rainbow#62]
This is related to #61 because I need it for Jinja files. In Jinja an `if`-block can contain `elif` and `else` statements:

```
{% if foo %}
<p>This is foo</p>
{% elif bar %}
<p>This is bar</p>
{% else %}
<p>Nothing to see here</p>
{% endif %}
```

The `elif` and `else` statements should have the same colour as the `if` and `endif` statements. Some sort of `between` or `contains` keyword in addition to `start` and `end` would be needed. It should be possible to specify more than one, but if that's too complicated then a more comples regex will have to do.

Or how about changing the format of the settings? Instead of every list item of `parentheses` being a string make it a dictionary with keys `start`, `end` and the optional `between`:

```
let g:rainbow_conf = {
    'c': {
        'parentheses': [
            " Highlight operators inside the parentheses (silly example, but you get the idea)
            { 'start': '/(/', 'end': '/)/', 'between': ['/\|\|/', '/\&\&/', '/\,/']},  " if (foo && bar)
            { 'start': '/\[/', 'end': '/\]/', 'between': ['/\,/']}                     " foo[bar, baz]
        ]
    }
}
```

I tried using the `operators` field, but `'operators': '/\v\{\% else \%\}/'` wouldn't find the `{% else %}`, I don't know why. It would also be trying to find `{% else %}` in every block.

I'm not sure about the name, `between` is too long IMO. Some other idea: `inside`, `step`, `continue`, `marks`.

**Comment by luochen1990** [comment]
I think `step` is what you want :)

**Comment by HiPhish** [comment]
Oh, that's cool. It wasn't documented in the readme and there is no Vim documentation for this plugin. I'm going to try it out right away.

**Comment by HiPhish** [comment]
After an hour of fiddling around I have now found out that the problem is my syntax file. The `start` and `end` are coloured properly, but the `step` takes on the colour of the syntax file rather than the parentheses. Only after disabling the syntax files did the `{% else %}` block get the proper colour.

If there some way of making Rainbow take precedence over the syntax file? Rainbow is installed via vim-plug, but the syntax file is a local file in `.vim/syntax/jinja.vim`.
