### ISSUE TITLE
parentheses are wrongly detected

### ISSUE THREAD

**Issue by Philipp-M** [luochen1990/rainbow#68]
In this code snippet, the parentheses are wrongly detected:
```Csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Player : MonoBehaviour {

    public Rigidbody rigid;
    // Update is called once per frame
    void Update () {
        if(Input.GetKey("w"))
            rigid.AddForce(new Vector3(0,0,10), ForceMode.Force);
    }
}
```
it looks like this:
![image](https://cloud.githubusercontent.com/assets/9267430/21851942/2b018818-d809-11e6-9e9f-88850930c6b8.png)

**Comment by luochen1990** [comment]
Maybe you are using some other third-party plugins for this filetype (c++? I'm not sure..) , If there is , please disable one and try again.

**Comment by Philipp-M** [comment]
It is C#, but I think I have also experienced it in different languages.
Somehow I can't reproduce it anymore, maybe it got fixed somehow.
I'm closing the issue therefore.
