### ISSUE TITLE
List comprehension is highlighted as error in julia

### ISSUE THREAD

**Issue by ngphuoc** [luochen1990/rainbow#69]
The closing square bracket is highlighted as error in ```[i for i in 1:10]```

![2017-01-27-114529_176x71_scrot](https://cloud.githubusercontent.com/assets/23738797/22358328/4837bad4-e492-11e6-9aa0-089c3058c853.png)

I am not sure if it is rainbow or julia plugin that causes this error. I also put an issue here https://github.com/JuliaEditorSupport/julia-vim/issues/94

**Comment by luochen1990** [comment]
I think there is some confliction between these plugins, you can either disable one of them or solve this confliction by yourself...

To disable rainbow for some specific filetypes, please reference the README.
