### ISSUE TITLE
Issues while using emmet-vim plugin

### ISSUE THREAD

**Issue by zhmars** [luochen1990/rainbow#73]
Hi,  I found it could make emmet-vim plugin unable to expand css well in html file
when disable rainbow, everything work fine. 

https://github.com/mattn/emmet-vim/issues/354
this issues may be helpful

**Comment by luochen1990** [comment]
If you use more than one third-party plugin for one filetype, there may be confliction.  You can either solve this confliction by hand or disable some of them. You can reference the README to know how to config this plugin to disable for some specific filetypes.
