### ISSUE TITLE
Spell-checking issues

### ISSUE THREAD

**Issue by boris-petrov** [luochen1990/rainbow#75]
I've been trying this plugin every once in a while for a few years now and I'm getting the same issue every time - spell checking is done for source code files. I'm seeing the issue in `Java`, `CoffeeScript`, `Handlebars templates` but not in `JavaScript` files for example. The "issue" is that words OUTSIDE of strings are highlighted as spelling mistakes - I want only strings to be checked. Is this possible? I've created a fork of `kien`'s Rainbow parentheses:

https://github.com/boris-petrov/rainbow_parentheses.vim

Which does exactly what I want with spellchecking. I would prefer to use this plugin instead but this issue is a blocker for me.

**Comment by luochen1990** [comment]
I think the spell checking problem can be solved for specific user, but I'm not sure what config is acceptable for everybody.

If you want to change the behavior of this plugin about spell checking, you can just fork this project and search the keywork "Spell" on the source code, and change something to find if it is what you want.

PS: I'm not sure what problem you have, maybe some picture will help you to explain the problem better :)

**Comment by boris-petrov** [comment]
Well, I guess my requests are pretty general - I don't want 90% of my code to be marked as with spelling errors - I KNOW that `int someVariableName = 10;` is wrongly spelled. :)

You can see the working version (with the modified version of `kien`'s Rainbow parentheses) that I use (it underlines only the spelling mistake in the string):

![working](https://cloud.githubusercontent.com/assets/278940/25273071/deaa7c8a-2692-11e7-9022-c6718729752d.png)

And what happens with your plugin:

![not-working](https://cloud.githubusercontent.com/assets/278940/25273077/e351d148-2692-11e7-8840-70d8fcb7e5aa.png)

It is underlining more than I would like (`asd` and `qwe` which are variable names). :)

As I said, the same happens with `CoffeeScript` and `Handlebars` templates, but not with `JavaScript` for some reason.

**Comment by luochen1990** [comment]
Yes, I can reproduce this issue, I need some time to fix it.

**Comment by luochen1990** [comment]
There is a lot of issue about the spell checking problem, and several pr which tried to fix this problem, but no one fixed it perfectly. https://github.com/luochen1990/rainbow/pull/59

**Comment by boris-petrov** [comment]
I've seen these issues, I've even written in some of them about the same problem a few years ago. :) The only help I could give is to check this commit: https://github.com/boris-petrov/rainbow_parentheses.vim/commit/8db068441b8e694ba866548524187d0cd26b60ca I'll also ping you if I have any other ideas.

**Comment by boris-petrov** [comment]
Adding a `@Spell` on this line:
https://github.com/luochen1990/rainbow/blob/master/plugin/rainbow.vim#L88
Fixes the issue for me. That is, from:

```vim
let def_rg = 'syn region %s matchgroup=%s containedin=%s contains=%s %s'
```

It becomes:

```vim
let def_rg = 'syn region %s matchgroup=%s containedin=%s contains=%s,@Spell %s'
```

I'm not sure why this was reverted in the first place (as [this](https://github.com/luochen1990/rainbow/commit/6bbf980377dcaccec946b5dd61b38aab2ef7e020) commit adds it)?

**Comment by luochen1990** [comment]
closing this, see #98 if you have any good idea :)
