### ISSUE TITLE
Long hangs with very large files and unbalanced parens

### ISSUE THREAD

**Issue by brandonson** [luochen1990/rainbow#84]
With very large files (5000-lines in the one I'm currently using) this will cause long delays with any sort of unbalanced paren, presumably as it tries to find the right way to highlight things.

Toggling this plugin to off seems to resolve the problem.

Does this plugin do any sort of mismatched paren detection? If not, could that be used to help fix this?

**Comment by luochen1990** [comment]
Maybe [this](http://vimdoc.sourceforge.net/htmldoc/syntax.html#:syn-sync) will help you, or `:h syn-sync` instead.
