### ISSUE TITLE
Any way to not share the color sequence for multiple start/end parentheses specifications?

### ISSUE THREAD

**Issue by mj-2017** [luochen1990/rainbow#87]
Say I want to highlight ()  and [] pairs.  If I type "([" the '[' will take on the second color in the guifgs sequence.  What I would like is for each start/end pair to be independent of the other start/end pairs regarding the color sequence.  Is that possible with this plugin?

**Comment by luochen1990** [comment]
It is possible if you modify the code of this plugin directly,  but it is not possible via configuration.

**Comment by mj-2017** [comment]
I see.  Could you provide the requisite change required to the plugin?

**Comment by mj-2017** [comment]
Just a gentle repeat request: Could you provide the requisite change required to the plugin?

**Comment by luochen1990** [comment]
@mj-2017 I'm sorry but I don't understand what you exactly want me to do...    Supporting this configuration is complicate and seems not worth.  And edit the code directly seems not very hard.

**Comment by mj-2017** [comment]
My apologies for not being more clear.  I am not asking for any changes to the configuration capability.  Rather, I was wondering if you could provide the code changes to the plugin that you refer to in order to get the plugin to operate in the manner I described.

**Comment by luochen1990** [comment]
nobody else need it, I think you can do it yourself :)
