### ISSUE TITLE
Rainbow doesn't work with syntax regions

### ISSUE THREAD

**Issue by schtibe** [luochen1990/rainbow#88]
If you use syntax regions in your file, e.g. javascript in html, the rainbow plugin doesn't work in the region.

I have a little example to show. Save this code to something like foo.txt:
```
Lala fofof

<script>

var foo = true;

if (foo) {
    alert("hey");
}

</script>
```

Then invoke following commands:
```
syntax include @javascript syntax/javascript.vim
syntax region jsregion start="<script>" end="</script>" contains=@javascript
```

The code between the `<script>` tags is now highlighted, but the parantheses aren't colored by the rainbow plugin.

**Comment by luochen1990** [comment]
try this:
```
syntax region jsregion start="<script>" end="</script>" contains=@javascript,@RainbowRegions
```
I'm not sure whether this will work.

**Comment by schtibe** [comment]
Nope, that doesn't work :/

**Comment by schtibe** [comment]
Sorry, I just quickly tested it, and now noticed something: 

It actually does work, but then the javascript highlighting is gone.

**Comment by luochen1990** [comment]
I think this problem is fixed in the latest version of rainbow.
Now the only problem is, the parentheses in the `<script>` tag is not highlighted.
