### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by kablondino** [luochen1990/rainbow#91]
This one is very small. In the Readme, it says to install with Vundle:
Plugin 'luochen1990/rainbow'

I forgot the .vim extension, making me feel stupid.

**Comment by luochen1990** [comment]
emmm,  I'm using `Bundle 'luochen1990/rainbow'` and works well,   I don't know why it not works for you...

**Comment by kablondino** [comment]
Hmm, very strange. I did a reinstall, and it worked this time. Nevermind...
