### ISSUE TITLE
Bracket problem with vim dev-icons

### ISSUE THREAD

**Issue by chernyshof** [luochen1990/rainbow#92]
Rainbow plugin causes appear of single bracket on the first line of nerd tree with vim-devicons.
[Please checkout this issue for more info](https://github.com/ryanoasis/vim-devicons/issues/165)

**Comment by luochen1990** [comment]
This may because that the plugin `vim-devicons` changed the default syntax definition for nerdtree, which cause some confliction. You can try this configuration to disable rainbow for nerdtree:
```
	let g:rainbow_conf = {
	\	'separately': {
	\		'nerdtree': 0,
	\	}
	\}
```

**Comment by chernyshof** [comment]
That solved my problem thanks!

**Comment by jtuz** [comment]
> This may because that the plugin `vim-devicons` changed the default syntax definition for nerdtree, which cause some confliction. You can try this configuration to disable rainbow for nerdtree:
> 
> ```
> 	let g:rainbow_conf = {
> 	\	'separately': {
> 	\		'nerdtree': 0,
> 	\	}
> 	\}
> ```

Thank you very much my friend, this solve my problem, was looking for the last 4 weeks until now I see your post.

**Comment by skylite21** [comment]
unfortunately this issue still persists when using :NERDTreeToggle with multiple buffers open. Is there any way to tell rainbow not to trigger on a NERDTree buffer ever?

**Comment by luochen1990** [comment]
@skylite21  just look above.

**Comment by skylite21** [comment]
@luochen1990 thanks but that is what I did ad it is not working when :NERDTreeToggle is triggered twice. 
Here is my minimal .vimrc:

```call plug#begin('~/.vim_plugged')


Plug  'https://github.com/junegunn/rainbow_parentheses.vim.git'
Plug 'https://github.com/scrooloose/nerdtree.git'
Plug 'https://github.com/tiagofumo/vim-nerdtree-syntax-highlight.git'
Plug 'https://github.com/ryanoasis/vim-devicons.git'
call plug#end()


" call rainbow_parentheses#activate()
au BufNewFile,BufRead *.js RainbowParentheses
au BufNewFile,BufRead *.jsx RainbowParentheses
au BufNewFile,BufRead *.config.js RainbowParentheses
au BufNewFile,BufRead *.json RainbowParentheses
au BufNewFile,BufRead *.py RainbowParentheses
au BufNewFile,BufRead *.php RainbowParentheses
let g:rainbow#max_level = 32
let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]

let g:rainbow_conf = {
\       'separately': {
\               'nerdtree': 0,
\       }
\}
```

[![asciicast](https://asciinema.org/a/P9FO3sLr6fZrz4X6AOnfqPWPr.svg)](https://asciinema.org/a/P9FO3sLr6fZrz4X6AOnfqPWPr)

**Comment by luochen1990** [comment]
@skylite21 You are not using my plugin ...

this is what you are using:

```
Plug  'https://github.com/junegunn/rainbow_parentheses.vim.git'
```

So, the configuration for my plugin doesn't work for it.  If you want to replace it with my plugin, README can help you :)

**Comment by skylite21** [comment]
Oh man. Sorry. I had yours commented out in my original config. I must have tried out different versions a while ago. It indeed works with your plugin without problem.
Thanks!
