### ISSUE TITLE
Breaks OCaml comments

### ISSUE THREAD

**Issue by wbthomason** [luochen1990/rainbow#93]
This plugin causes OCaml comments (which use the syntax `(* Your comment here *)`) to not be highlighted as comments. I've tried playing around with an OCaml entry in the `separately` field of `g:rainbow_conf`, but wasn't able to find a way to make the `(* *)` not be highlighted with this plugin. Is there anything I should try?

**Comment by luochen1990** [comment]
Yes, you can do that via advanced configuration like following:

```
	let g:rainbow_conf = {
	\	'separately': {
	\		'ocaml': {
	\			'parentheses': ['start=/(\*\@!/ end=/)/ fold contains=@colorableGroup'],
	\		}
	\	}
	\}
```

The trick is about zero-width regular-expression pattern feature which is supported by Vim. You can read more about it via `:h zero-width`
