### ISSUE TITLE
rainbow plugin interferes with bash syntax highlighting in if-then-else clauses

### ISSUE THREAD

**Issue by srgvg** [luochen1990/rainbow#95]
With `g:rainbow_active = 1` I get this:
![20180304155037](https://user-images.githubusercontent.com/382239/36948315-57473bac-1fd9-11e8-8036-3bd99d8a8def.png)
Checking the syntax highlighting groups I get `hi<shCondError> trans<shCondError> lo<Error>` (with the cursor on the pink highlighted `then`).
With the cursor on the `if` I get `hi<rainbow_p0> trans<rainbow_p0> lo<rainbow_p0>`.

Disabling (or toggling the plugin) gets me what I IMHO should have:
![20180304182606](https://user-images.githubusercontent.com/382239/36948324-8893d4d6-1fd9-11e8-9a51-bac4a201c570.png)
The syntax highlighting groups are now `hi<shConditional> trans<shConditional> lo<Conditional>` on the `then`.
On the `if` I get `hi<shConditional> trans<shConditional> lo<Conditional>`.

FYI, checking the syntax highlighting groups is done with this snippet in .vimrc:
```
" http://vim.wikia.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor
map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```

**Comment by luochen1990** [comment]
The reason is, in the file `syntax/sh.vim`, there is the following lines:

```
syn keyword shConditional contained elif else then
if !exists("g:sh_no_error")
 syn keyword shCondError elif else then
endif
```

So, a quick solution will be add `let g:sh_no_error = 1` into your vimrc .
Another solution is define your own parentheses for `sh` files separately.

**Comment by nedbat** [comment]
@luochen1990 Your explanation about why the words are highlighted as errors makes sense, but doesn't explain why rainbow is involved?  Disabling rainbow makes the problem go away, why?  Rainbow doesn't mention `g:sh_no_error`, so why does it trigger this behavior?

If I run vim without rainbow, this sh.vim file doesn't highlight "elif" as an error, but I don't understand why.

**Comment by nedbat** [comment]
If I change my rainbow settings from:
```
\       'sh': {
\           'parentheses': [['\(^\|\s\)\S*()\s*{\?\($\|\s\)','_^{_','}'], ['\(^\|\s\)if\($\|\s\)','_\(^\|\s\)\(then\|else\|elif\)\($\|\s\)_','\(^\|\s\)fi\($\|\s\)'], ['\(^\|\s\)for\($\|\s\)','_\(^\|\s\)\(do\|in\)\($\|\s\)_','\(^\|\s\)done\($\|\s\)'], ['\(^\|\s\)while\($\|\s\)','_\(^\|\s\)\(do\)\($\|\s\)_','\(^\|\s\)done\($\|\s\)'], ['\(^\|\s\)case\($\|\s\)','_\(^\|\s\)\(\S*)\|in\|;;\)\($\|\s\)_','\(^\|\s\)esac\($\|\s\)']],
\       },
```
to:
```
\       'sh': 0,
```
then the problem goes away.
