### ISSUE TITLE
Broken #ifdef/#endif match

### ISSUE THREAD

**Issue by j5shi** [luochen1990/rainbow#96]
### **Describe the bug**
```c
#ifdef __cplusplus
extern "C" {
#endif
```
the `#endif` is considered not to match with `#ifdef` in above C/CPP code.

### **To Reproduce**

- add the following config to your .vimrc
```vim
    let g:rainbow_conf = {
    \   'separately': {
    \       'vim': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/if/ step=/elseif\|else/ end=/|\?endif/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody', 'start=/if/ step=/elseif\|else/ end=/|\?endif/ fold containedin=vimFuncBody'],
    \       },
    \       'cpp': {
    \           'parentheses': ['start=/(/ end=/)/', 
    \                           'start=/\[/ end=/\]/', 
    \                           'start=/{/ end=/}/ fold', 
    \                           'start=/#ifdef\|#ifndef\|#ifeq\|#if/ step=/#elif\|#else/ end=/#endif/'],
    \       },
    \       'c': {
    \           'parentheses': ['start=/(/ end=/)/', 
    \                           'start=/\[/ end=/\]/', 
    \                           'start=/{/ end=/}/ fold', 
    \                           'start=/#ifdef\|#ifndef\|#ifeq\|#if/ step=/#elif\|#else/ end=/#endif/'],
    \       }
    \   }
    \}
```
- create a C or CPP file
- add the code snippet in bug description section

### **Expected behavior**
the `#endif` is should match with `#ifdef` in above C/CPP code and have the same color.

### **Screenshots**
![capture](https://user-images.githubusercontent.com/6829121/40607599-89068bfc-629b-11e8-99ef-09fc9bb2e81a.JPG)

### **Additional context**
No.

**Comment by luochen1990** [comment]
The `{` after `extern "C"` is considered as a parenthesis. It seems complicate to avoid this problem.

**Comment by luochen1990** [comment]
Actually, nobody can tell whether there is a right parenthesis following.

**Comment by j5shi** [comment]
Actually it's not about whether there's a closed parenthesis following or not, it's about nested parenthesis/brackets/braces.

**Comment by luochen1990** [comment]
You can replace `#ifdef` and `#endif` into `(` and `)`,  it's almost the same thing.
